name: DEPLOY TO STAGING

on:
    pull_request:
        types: [closed]
        branches:
            - dev

jobs:
    aws-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: dev
            - uses: actions/setup-node@v1
            - run: npm install
            - run: npm run bundle
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'deploy/'
                  REMOTE_HOST: 'project3.eaglesoftwareteam.com'
                  REMOTE_USER: ubuntu
                  TARGET: 'nodeapps/2022/project3/t2'
            - name: Execute SSH commmands on remote server
              uses: JimCronqvist/action-ssh@master
              env:
                  NAME: 'Root'
              with:
                  hosts: 'ubuntu@project3.eaglesoftwareteam.com'
                  privateKey: ${{ secrets.SERVER_SSH_KEY }}
                  debug: false
                  command: |
                      cd nodeapps/2022/project3/t2
                      npm install
                      sudo systemctl stop schedule-t2-backend
                      sudo cp schedule-t2-backend.service /lib/systemd/system/schedule-t2-backend.service
                      sudo systemctl daemon-reload
                      sudo systemctl start schedule-t2-backend